ModuleSystem:loadModule('manage')
ModuleSystem:loadModule('combox')
ModuleSystem:loadModule('help_bar')
ModuleSystem:loadModule('demo')
ModuleSystem:loadModule('copilot')
ModuleSystem:loadModule('map')
